# This is a basic workflow to help you get started with Actions

name: CI 
        
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]
    types: [converted_to_draft, ready_for_review]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  label_draft:
    if: github.event.pull_request.draft == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: set draft label
        uses: jinmayamashita/ready-for-review@1.0.0
        with:
          ready-for-review-label: 'ReadyForReview'
          in-progress-label: 'In Progress'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          
  label_ready:
    if: github.event.pull_request.draft == false
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: set ready label
        uses: jinmayamashita/ready-for-review@1.0.0
        with:
          in-progress-label: 'In Progress'
          ready-for-review-label: 'ReadyForReview'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
